init:
	echo "Compiling..."
	g++ assembler.cpp -o rasm
	echo "Compiled successfully!"
	echo "Setting up!"
	rm "../Programs/rasm"
	mv rasm "../Programs"

clean:
	echo "Deleting executable..."
	rm rasm
	echo "Cleanup successfull"
